$(function(){
	$("#inputSearch").focus(function(){
		$(this).addClass("focus");
		if($(this).val()==this.defaultValue){
			$(this).val("");
			}
		}).blur(function(){
		$(this).removeClass("focus");
		if($(this).val()=='')
		{
			$(this).val(this.defaultValue);}
		}).keyup(function(e){
			if(e.which==13)
			{
				if($("#inputSearch").val()==""){
					alert("请输入商品名称");}
					else{
				alert("搜索完成！");}
			}
			});
	
	});